In [1]:
suppressMessages(library(rwwa))
png_res <- 240

# load covariates
gmst <- read.table("ts-obs/gmst.dat", col.names = c("year", "gmst"))
gmst$gmst <- gmst$gmst - gmst$gmst[gmst$year == 2026]
nao <- load_ts("ts-obs/med-storms_nao-djf_era5-stn.dat", col.names = c("year", "nao"))

cov_df <- merge(gmst, nao)
cov_df$gmst <- cov_df$gmst - cov_df$gmst[cov_df$year == 2026]
cov_df$nao_res <- resid(lm(nao ~ gmst, cov_df))

# define factual & counterfactual climates
cov_2026 <- cov_df[cov_df$year == 2026,c(-1),drop = F]
cov_cf <- rbind("pi" = cov_2026 - c(1.3,0,0),
                "naoneutral" = c(cov_2026$gmst, 0,0),
                "pineutral" = c(-1.3, 0,0))

# Tables of results

In [2]:
varnm <- "rx1day-ondjfm"
rnm <- "s"

res <- read.csv(paste0("res-obs_",varnm,"_",rnm,".csv"), row.names = "X")
# res <- res[!grepl("naodet", rownames(res)),]
# res <- res[grepl("era5|eobs", rownames(res)),]

In [3]:
cols <- c("event", "return.period", "dI.rel.pi", "dI.rel.naoneutral", "PR.pi", "PR.naoneutral")
tbl <- data.frame(sapply(cols, function(cnm) {
    apply(signif(res[,grepl(cnm, colnames(res)),drop = F], 3), 1, function(r) {
        paste0(r[1], " (",r[2], ", ", r[3], ")")
    })
}))
tbl$event <- gsub(" .+","",tbl$event)
tbl[c(2,5,1,4,3),]

                             event return.period    dI.rel.pi
ERA5 - GMST + NAO            40.4  39.8 (8.99, Inf) 23 (-0.257, 47.7)
EObs - GMST + NAO            50.8  40 (14.2, 746)   49.2 (23.6, 77.3)
ERA5 - GMST only             40.4  82.6 (13.2, Inf) 17.7 (-4.36, 43.4)
EObs - GMST only (1950-2026) 48.3  40 (16.4, 297)   42.4 (17.8, 65.6)
EObs - GMST only (1920-2026) 46.5  40 (15, 214)     38.2 (20.8, 54.8)
                             dI.rel.naoneutral  PR.pi
ERA5 - GMST + NAO            5.36 (0.664, 9.58) 64.9 (0.983, Inf)
EObs - GMST + NAO            4.44 (-1.13, 9.33) 48.4 (2.62, Inf)
ERA5 - GMST only             0 (0, 0)           52.8 (0.364, Inf)
EObs - GMST only (1950-2026) 0 (0, 0)           29.5 (2.16, Inf)
EObs - GMST only (1920-2026) 0 (0, 0)           26.3 (3.11, 189000)
                             PR.naoneutral
ERA5 - GMST + NAO            2.1 (1.15, 29.2)
EObs - GMST + NAO            1.42 (0.929, 4.57)
ERA5 - GMST only             1 (1, 1)
EObs - GMST only (1950-2026) 1 (1, 1)
EObs - GMST only (1920-2026) 1 (1, 1)

# Figures for obs discussion

## Trends vs covariates

In [5]:
varnm <- "rx1day-ondjfm"

for (ds_nm in c("eobs", "era5")[1]) {
    for (rnm in c("s","n")[1]) {

        df <- merge(cov_df, load_ts(paste0("ts-obs/med-storms_",varnm,"_",rnm,"_",ds_nm,".dat"), col.names = c("year", "x")))
        mdl <- fit_ns("gev", "fixeddisp", data = df, covnm = c("gmst", "nao"), varnm = "x", lower = F)
        
        ylim <- list("s" = c(0,60), "n" = c(0,100))[[rnm]]

        if (ds_nm == "eobs" & rnm == "s") ev <- NA else ev <- mdl$ev
        
        png(paste0("fig-obs/sr-trendplots_",varnm,"_",rnm,"_",ds_nm,".png"), h = png_res, w = png_res * 3); {
            prep_window(c(1,3), cex.axis = 1.25, mar = c(4,2,3,1), oma = c(0,3,0,0))

            plot_covtrend(mdl, "gmst", ylab = "", xlab = "", legend_pos = NA, ylim = ylim, ev = ev)
            mtext("Maximum 1-day precipitation (mm)", side = 2, line = 3.25)
            mtext("GMST anomaly wrt 2026", side = 1, line = 2.75)
            mtext("(a)", side = 3, line = 0.75, adj = 0, font = 2)
            
            plot_covtrend(mdl, "nao", ylab = "", xlab = "", legend_pos = NA, ylim = ylim, ev = ev)
            mtext("Normalised NAO index", side = 1, line = 2.75)
            mtext("(b)", side = 3, line = 0.75, adj = 0, font = 2)
            
            plot_trend(mdl, ylab = "", xlab = "", legend_pos = NA, ylim = ylim, ev = ev, ev_year = 2026)
            mtext("Year", side = 1, line = 2.75)
            mtext("(c)", side = 3, line = 0.75, adj = 0, font = 2)
            
        }; dev.off()
    }
}

## Return level plots

In [15]:
for (ds_nm in c("eobs", "era5")[1]) {
    for (rnm in c("s","n")[1]) {
    
        df <- merge(cov_df, load_ts(paste0("ts-obs/med-storms_",varnm,"_",rnm,"_",ds_nm,".dat"), col.names = c("year", "x")))
        mdl <- fit_ns("gev", "fixeddisp", data = df, covnm = c("gmst", "nao"), varnm = "x", lower = F)

        if (ds_nm == "eobs" & rnm == "s") {
            rl40 <- eff_return_level(mdl, rp = 40, fixed_cov = cov_2026)
            mdl <- fit_ns(dist = mdl$dist, type = mdl$type, data = mdl$data, varnm = mdl$varnm, covnm = mdl$covnm, lower = mdl$lower, ev = rl40, ev_year = 2026)
        }
        
        ylim <- list("s" = c(0,60), "n" = c(0,100))[[rnm]]
        
        png(paste0("fig-obs/sr-rlplots_",varnm,"_",rnm,"_", ds_nm,".png"), h = png_res, w = png_res * 3); {
            prep_window(c(1,2), cex.axis = 1.25, mar = c(4,2,3,1), oma = c(0,3,0,0))
        
            plot_returnlevels(mdl, cov_f = cov_2026, cov_cf = cov_cf["pi",,drop = F], ylab = "", legend_pos = NA, nsamp = 500)
            mtext("Maximum 1-day precipitation (mm)", side = 2, line = 3.25)
            mtext("(a)", side = 3, line = 0.75, adj = 0, font = 2)
        
            plot_returnlevels(mdl, cov_f = cov_2026, cov_cf = cov_cf["naoneutral",,drop = F], ylab = "", legend_pos = NA, nsamp = 500)
            mtext("(b)", side = 3, line = 0.75, adj = 0, font = 2)
            
        }; dev.off()
    }
}

# Tables of model eval & results

In [13]:
varnm <- "rx1day-ondjfm"
rnm <- "n"

In [14]:
# load & clean all the data
res_obs <- read.csv(paste0("res-obs_",varnm,"_",rnm,".csv"), row.names = "X")
res_obs <- res_obs[!grepl("det|only", rownames(res_obs)),]
res_obs <- res_obs[!grepl("chirps|cpc|mswep", rownames(res_obs)),]
rownames(res_obs) <- toupper(sapply(strsplit(rownames(res_obs), "_| - "), "[", 1))
res_obs <- res_obs[c("EOBS", "ERA5"),]
rownames(res_obs) <- gsub("EOBS", "E-Obs", rownames(res_obs))

In [15]:
res_cordex <- read.csv(paste0("res-cordex_",varnm,"_",rnm,"_gmst+nao_with-eval.csv"), row.names = "X.1")
rownames(res_cordex) <- gsub("i1p1_", "i1p1 ",rownames(res_cordex))


res_hr <- read.csv(paste0("res-highresmip_",varnm,"_",rnm,"_gmst+nao_with-eval.csv"), row.names = "X.1")
# manually filter out duplicated runs - keep 'good' rather than 'reasonable', then take higher-resolution version
if (rnm == "s" & varnm == "rx1day-ondjfm") {
    dup <- c('EC-Earth3P-HR', 'HadGEM3-GC31-HM', 'HadGEM3-GC31-LM', 'MPI-ESM1-2-HR')
} else if (rnm == "n" & varnm == "rx1day-ondjfm") {
    dup <- c('MPI-ESM1-2-HR')
}
res_hr[dup, "overall"] <- "duplicate"

mdl_res <- rbind.fill(res_cordex, res_hr)
rownames(mdl_res) <- c(rownames(res_cordex), rownames(res_hr))

## Evaluation

In [16]:
obs_eval <- data.frame("Event" = signif(res_obs$event.magnitude_est,3),
                     "Seasonal" = "",
                     "Spatial" = "", 
                     "Dispersion" = apply(signif(res_obs[,grepl("disp", colnames(res_obs)),drop = F], 3), 1, function(r) paste0(r[1], " (",r[2], ", ", r[3], ")")),
                     "Shape parameter" = apply(signif(res_obs[,grepl("shape", colnames(res_obs)),drop = F], 3), 1, function(r) paste0(r[1], " (",r[2], ", ", r[3], ")")),
                     "NAO correlation" = apply(signif(res_obs[,grepl("cor", colnames(res_obs)),drop = F], 3), 1, function(r) paste0(r[1], " (",r[2], ", ", r[3], ")")),
                     "Overall" = "",
                     "Keep" = "")

mdl_eval <- data.frame("Event" = signif(mdl_res$rp_value,3),
                     "Seasonal" = mdl_res$seasonal,
                     "Spatial" = mdl_res$spatial, 
                     "Dispersion" = apply(signif(mdl_res[,grepl("disp_", colnames(mdl_res)),drop = F], 3), 1, function(r) paste0(r[1], " (",r[2], ", ", r[3], ")")),
                     "Shape parameter" = apply(signif(mdl_res[,grepl("shape_", colnames(mdl_res)),drop = F], 3), 1, function(r) paste0(r[1], " (",r[2], ", ", r[3], ")")),
                     "NAO correlation" = apply(signif(mdl_res[,grepl("corr_", colnames(mdl_res)),drop = F], 3), 1, function(r) paste0(r[1], " (",r[2], ", ", r[3], ")")),
                     "Overall" = mdl_res$overall,
                     "Keep" = mdl_res$include, row.names = rownames(mdl_res))

write.csv(rbind(obs_eval, mdl_eval), paste0("tbl_model-eval_",varnm,"_",rnm,".csv"))

## Results

In [17]:
cols <- c("dI.rel.pi", "NA", "dI.rel.naoneutral", "PR.pi", "NA", "PR.naoneutral")
obs_df <- data.frame(sapply(cols, function(cnm) apply(signif(res_obs[,grepl(cnm, colnames(res_obs)),drop = F], 3), 1, 
                                                        function(r) paste0(r[1], " (",r[2], ", ", r[3], ")"))))
# colnames(obs_df) <- colnames(mdl_df)[1:length(colnames(obs_df))]
obs_df

      dI.rel.pi          NA.         dI.rel.naoneutral  PR.pi
E-Obs 39.3 (16.4, 70.5)  NA (NA, NA) 2.66 (-1.04, 6.67) 7.12 (2.71, 46.9)
ERA5  19.1 (-1.01, 47.3) NA (NA, NA) 1.61 (-1.75, 5.29) 3.45 (0.925, Inf)
      NA..1       PR.naoneutral
E-Obs NA (NA, NA) 1.1 (0.958, 1.35)
ERA5  NA (NA, NA) 1.09 (0.888, 1.36)

In [18]:
res_obs

      mu0_est  mu0_lower mu0_upper sigma0_est sigma0_lower sigma0_upper
E-Obs 41.23010 35.4586   48.19274  9.046446   6.747173     11.05226
ERA5  42.47967 36.3729   50.95261  9.659773   7.567981     12.35813
      alpha.gmst_est alpha.gmst_lower alpha.gmst_upper shape_est  ⋯
E-Obs 10.503897       4.2451578       19.68916         -0.1127856 ⋯
ERA5   5.699321      -0.2937576       15.35593         -0.1844265 ⋯
      cor.gmst.nao_upper alpha.nao.res_est alpha.nao.res_lower
E-Obs 0.4136777          NA                NA
ERA5  0.4136777          NA                NA
      alpha.nao.res_upper cor.x.nao.res_est cor.x.nao.res_lower
E-Obs NA                  NA                NA
ERA5  NA                  NA                NA
      cor.x.nao.res_upper cor.gmst.nao.res_est cor.gmst.nao.res_lower
E-Obs NA                  NA                   NA
ERA5  NA                  NA                   NA
      cor.gmst.nao.res_upper
E-Obs NA
ERA5  NA

In [19]:
cols <- c("attr_dI.rel.pi", "proj_dI.rel", "attr_dI.rel.naoneutral", "attr_PR.pi", "proj_PR", "attr_PR.naoneutral")
mdl_df <- data.frame(cbind(sapply(cols, function(cnm) apply(signif(mdl_res[,grepl(cnm, colnames(mdl_res)),drop = F], 3), 1, 
                                                           function(r) paste0(r[1], " (",r[2], ", ", r[3], ")")))))
mdl_df <- mdl_df[mdl_res$include == "Y",]
mdl_df

                                    attr_dI.rel.pi       proj_dI.rel
CNRM-CM5_r1i1p1 ALADIN53            1.1 (-17.7, 21.8)    6.09 (-0.0448, 11.4)
CNRM-CM5_r1i1p1 HIRHAM5             2.01 (-13.8, 19.7)   7.15 (1.04, 12)
CNRM-CM5_r1i1p1 RACMO22E            -0.609 (-16.5, 19.1) 6.49 (0.7, 12.1)
CNRM-CM5_r1i1p1 RegCM4-6            -0.99 (-21.9, 25.3)  5.98 (-0.424, 11.9)
CNRM-CM5_r1i1p1 REMO2015            3.37 (-11.3, 21.5)   8.03 (2.65, 12.3)
CNRM-CM5_r1i1p1 WRF381P             10.4 (-6.93, 30.7)   7.85 (1.44, 13.4)
HadGEM2-ES_r1i1p1 COSMO-crCLIM-v1-1 5.98 (-10.7, 25.2)   0.413 (-5.2, 6.46)
HadGEM2-ES_r1i1p1 HadREM3-GA7-05    7.49 (-6.57, 25.8)   0.279 (-4.75, 5.44)
HadGEM2-ES_r1i1p1 WRF381P           10.5 (-7.21, 26.8)   3.27 (-2.16, 7.94)
IPSL-CM5A-MR_r1i1p1 RACMO22E        13.8 (-2.69, 34.7)   -0.0478 (-4.86, 4.71)
IPSL-CM5A-MR_r1i1p1 RCA4            22.9 (5.52, 43.5)    4.57 (-1.15, 10.2)
IPSL-CM5A-MR_r1i1p1 REMO2015        19.3 (0.395, 39.2)   2.65 (-2.31, 7.92)
MPI-ESM-LR_r1i1p1 CCLM4-8-17        12.4 (0.203, 26.3)   6.57 (2.14, 11.7)
MPI-ESM-LR_r1i1p1 COSMO-crCLIM-v1-1 7.28 (-5.76, 20.8)   3.82 (-1.8, 9.26)
MPI-ESM-LR_r1i1p1 HadREM3-GA7-05    9.64 (-3.83, 25.4)   5.55 (0.489, 10.3)
MPI-ESM-LR_r1i1p1 HIRHAM5           5.14 (-6.8, 17.8)    5.91 (1.08, 10.1)
MPI-ESM-LR_r1i1p1 RCA4              9.1 (-13.7, 33)      8.43 (2.05, 15.3)
MPI-ESM-LR_r1i1p1 RegCM4-6          23.2 (-5.59, 50.9)   6.13 (-1.51, 15.6)
CNRM-CM6-1-HR                       9.46 (-5.9, 27.5)    4.94 (-3.87, 13.5)
EC-Earth3P                          -8.11 (-12.6, 11.5)  -1.81 (-12.5, 8.53)
HadGEM3-GC31-HM                     -0.795 (-7.47, 23.4) -6.66 (-11.8, 2.21)
MPI-ESM1-2-XR                       -0.708 (-6.53, 20.2) 1.94 (-8.69, 13.3)
                                    attr_dI.rel.naoneutral attr_PR.pi
CNRM-CM5_r1i1p1 ALADIN53            4.3 (0.0579, 8.22)     1.08 (0.354, 5.04)
CNRM-CM5_r1i1p1 HIRHAM5             3.13 (-1.19, 7.63)     1.16 (0.431, 6.86)
CNRM-CM5_r1i1p1 RACMO22E            2.15 (-2.1, 6.49)      0.956 (0.379, 10.1)
CNRM-CM5_r1i1p1 RegCM4-6            3.04 (-1.96, 8.48)     0.935 (0.311, 9.34)
CNRM-CM5_r1i1p1 REMO2015            3.51 (-0.931, 8.29)    1.3 (0.473, 10.5)
CNRM-CM5_r1i1p1 WRF381P             -0.527 (-4.51, 4.16)   1.99 (0.668, 12.8)
HadGEM2-ES_r1i1p1 COSMO-crCLIM-v1-1 3.6 (-0.553, 8.41)     1.4 (0.577, 33.6)
HadGEM2-ES_r1i1p1 HadREM3-GA7-05    4.57 (0.816, 9.15)     1.55 (0.688, 8.4)
HadGEM2-ES_r1i1p1 WRF381P           1.54 (-2.56, 5.83)     1.99 (0.683, 37.4)
IPSL-CM5A-MR_r1i1p1 RACMO22E        4.69 (0.655, 8.7)      2.36 (0.854, 43.6)
IPSL-CM5A-MR_r1i1p1 RCA4            2.72 (-2.12, 7.57)     4.18 (1.45, Inf)
IPSL-CM5A-MR_r1i1p1 REMO2015        4.97 (0.404, 9.71)     3.05 (1.02, 33)
MPI-ESM-LR_r1i1p1 CCLM4-8-17        2.3 (-1.68, 6.43)      2.49 (1.01, 860)
MPI-ESM-LR_r1i1p1 COSMO-crCLIM-v1-1 0.999 (-3.23, 6.3)     1.62 (0.697, 6.4)
MPI-ESM-LR_r1i1p1 HadREM3-GA7-05    0.316 (-3.98, 5.16)    2.11 (0.741, 13.2)
MPI-ESM-LR_r1i1p1 HIRHAM5           0.617 (-3.66, 4.61)    1.49 (0.588, 4.84)
MPI-ESM-LR_r1i1p1 RCA4              -0.104 (-5.57, 7.53)   1.77 (0.449, 11)
MPI-ESM-LR_r1i1p1 RegCM4-6          -2.93 (-9.13, 2.69)    3.86 (0.785, Inf)
CNRM-CM6-1-HR                       2.89 (-2.42, 8.24)     2 (0.674, 7.61)
EC-Earth3P                          -0.448 (-3.29, 3.56)   0.627 (0.472, 2.23)
HadGEM3-GC31-HM                     5.33 (0.54, 10.5)      0.949 (0.62, 10.8)
MPI-ESM1-2-XR                       1.95 (-2.94, 6.7)      0.954 (0.661, 13.3)
                                    proj_PR             attr_PR.naoneutral
CNRM-CM5_r1i1p1 ALADIN53            1.45 (0.997, 1.98)  1.35 (1, 1.99)
CNRM-CM5_r1i1p1 HIRHAM5             1.58 (1.08, 2.11)   1.26 (0.911, 1.85)
CNRM-CM5_r1i1p1 RACMO22E            1.49 (1.05, 2.05)   1.18 (0.859, 1.69)
CNRM-CM5_r1i1p1 RegCM4-6            1.47 (0.969, 2.1)   1.24 (0.875, 2.28)
CNRM-CM5_r1i1p1 REMO2015            1.71 (1.23, 2.17)   1.32 (0.928, 1.92)
CNRM-CM5_r1i1p1 WRF381P             1.54 (1.09, 2.08)   0.968 (0.733, 1.29)
HadGEM2-ES_r1i1p1 COSMO-crCLIM-v1-1 1.02 (0.752, 1.38)  1.22 (0.969, 1.72)
HadGEM2-ES_r1i1p1 HadREM3-GA7-05    1.02 (0.745, 1.34)  1.3 (1.05, 1.82)
HadGEM2-ES_r1i1p1 WRF381P           1.2 (0.882, 1.58)   1.1 (0.848, 1.53)
IPSL-CM5A-MR_r1i1p1 RACMO22E        0.997 (0.746, 1.29) 1.32 (1.04, 1.76)
IPSL-CM5A-MR_r1i1p1 RCA4            1.26 (0.943, 1.72)  1.17 (0.876, 1.74)
IPSL-CM5A-MR_r1i1p1 REMO2015        1.15 (0.878, 1.51)  1.32 (1.03, 1.62)
MPI-ESM-LR_r1i1p1 CCLM4-8-17        1.52 (1.14, 2.22)   1.17 (0.886, 1.56)
MPI-ESM-LR_r1i1p1 COSMO-crCLIM-v1-1 1.27 (0.887, 1.83)  1.07 (0.805, 1.56)
MPI-ESM-LR_r1i1p1 HadREM3-GA7-05    1.46 (1.04, 1.98)   1.02 (0.745, 1.57)
MPI-ESM-LR_r1i1p1 HIRHAM5           1.49 (1.08, 2.05)   1.05 (0.75, 1.46)
MPI-ESM-LR_r1i1p1 RCA4              1.6 (1.14, 2.27)    0.994 (0.712, 1.77)
MPI-ESM-LR_r1i1p1 RegCM4-6          1.4 (0.92, 2.37)    0.856 (0.642, 1.18)
CNRM-CM6-1-HR                       1.37 (0.768, 2.32)  1.23 (0.857, 2.01)
EC-Earth3P                          0.894 (0.44, 1.69)  0.973 (0.814, 1.24)
HadGEM3-GC31-HM                     0.644 (0.439, 1.15) 1.46 (1.04, 2.28)
MPI-ESM1-2-XR                       1.11 (0.486, 1.95)  1.15 (0.804, 1.61)

In [20]:
colnames(obs_df) <- colnames(mdl_df)
df <- data.frame(rbind.fill(obs_df, mdl_df), row.names = c(rownames(obs_df), rownames(mdl_df)))

In [21]:
write.csv(df, paste0("tbl_model-res_",varnm,"_",rnm,".csv"))